[platformio]
include_dir = Core/Inc
src_dir = Core/Src
default_envs =
  iheater_rev1_1_pulse
  iheater_rev1_0
  iheater_rev1_1
  idryer_rev1_1
lib_dir = Lib

; General settings for all environments
[env]
platform = ststm32
board = genericSTM32F042F6
framework = stm32cube
upload_protocol = stlink
lib_archive = no
build_type = debug
debug_speed = 1800
debug_load_mode = modified
extra_scripts = post:convert_to_bin.py
; do not reset board upon connecting
debug_init_cmds =
  target extended-remote $DEBUG_PORT
  $INIT_BREAK
  monitor halt
  monitor init
  monitor resume

[env:iheater_rev1_0]
build_flags =
      -O0
      -ggdb
      -DDEVICE_PROFILE=DEVICE_PROFILE_HEATER
      -DBOARD_REVISION=BOARD_REV_1_0

[env:iheater_rev1_1]
build_flags =
      -O0
      -ggdb
      -DDEVICE_PROFILE=DEVICE_PROFILE_HEATER
      -DBOARD_REVISION=BOARD_REV_1_1

[env:iheater_rev1_1_pulse]
build_flags =
      -O0
      -ggdb
      -DDEVICE_PROFILE=DEVICE_PROFILE_HEATER
      -DBOARD_REVISION=BOARD_REV_1_1
      -DINPUT_MODE=INPUT_MODE_DIGITAL_PULSE

[env:idryer_rev1_1]
build_flags =
      -O0
      -ggdb
      -DDEVICE_PROFILE=DEVICE_PROFILE_DRYER
      -DBOARD_REVISION=BOARD_REV_1_1
